### ISSUE TITLE
Test final solution

### ISSUE THREAD

**Issue by krukle** [krukle/energy-gateway#9]

**Comment by oenstrom** [comment]
- [ ] #4 
- [ ] #7 
- [x] #28 in combination with ota

**Comment by oenstrom** [comment]
# Test serial IO with OTA

Test was performed at 20Hz. No messages were missed even though ota was being run simultanesously. 

## Log from Energy gateway device.

![Energy gateway Uart](https://user-images.githubusercontent.com/18578458/221821753-6102e605-5180-4802-8852-6c6e43276f43.png)

# Log from external device.

![External device Uart](https://user-images.githubusercontent.com/72295233/221821991-8fc00e36-0811-42b8-8bf6-4ae4627cf0e6.png)
